#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# rebuild ui


# copy default config files if they don't exist
cp -nrv /defaults/nginx/* /etc/nginx/

# generate template configs
script=/etc/s6-overlay/s6-rc.d/init-nginx/convert
templates=/etc/nginx/site-templates
find $templates -type f -name "*.conf.template" -exec $script {} \;

# copy pre-generated dhparams or generate if needed
if [[ ! -f /etc/nginx/dhparams.pem ]]; then
    cp /defaults/nginx/dhparams.pem.sample /etc/nginx/dhparams.pem
fi
if ! grep -q 'PARAMETERS' "/etc/nginx/dhparams.pem"; then
    curl -o /etc/nginx/dhparams.pem -L "https://ssl-config.mozilla.org/ffdhe4096.txt"
fi
