name: Build and Push Docker images to Docker Hub

on:
  push:
    paths:
      - .github/workflows/openems-ui.yml

jobs:
  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push Docker image for openems-ui
        uses: docker/build-push-action@v5
        with:
          context: tools/docker/openems-ui
          push: true
          tags: manoj1210/openems-ui:latest
      
      - name: Build and push Docker image for openems-edge
        uses: docker/build-push-action@v5
        with:
          context: tools/docker/openems-edge
          push: true
          tags: manoj1210/openems-edge:latest
