name: Build OpenEMS Docker Image

on:
  push:
    paths:
      - .github/workflows/openems-ui.yml

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [openems-edge, openems-backend, openems-ui]
        include:
          - image: openems-edge
            dockerfile: tools/docker/openems-edge/Dockerfile
            repo: manojniit/openems-edge
          - image: openems-backend
            dockerfile: tools/docker/openems-backend/Dockerfile
            repo: manojniit/openems-backend
          - image: openems-ui
            dockerfile: tools/docker/openems-ui/Dockerfile
            repo: manojniit/openems-ui

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get cleaned branch name
        id: clean_name
        run: |
          REF_NAME=$(echo "${{ github.ref }}" | sed -e 's/refs\/heads\///' -e 's/refs\/tags\///' -e 's/release\/v//')
          echo "branch=${REF_NAME}-test" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ matrix.repo }}
          labels: |
            org.opencontainers.image.authors=manojniit
            org.opencontainers.image.title=manojniit ${{ matrix.image }}
            org.opencontainers.image.vendor=manojniit

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
